image: python:3.9 

stages:
  - build
  - test

build-job:
  stage: build
  script:
  - echo "Compiling the code..."
  - echo "Compile complete."

before_script:
  - python -V
  - pip install -r backend/requirements.txt 
  - pip install coverage

test:
  stage: test
  script:
     # Running code quality checks using flake8
    - echo "Running unit tests... This will take about 60 seconds."
    - sleep 10
    - coverage run backend/test_module.py # Running the tests. 
    - coverage report
  coverage: '/TOTAL.*?(\d+\%)$/'
