image: python:3.9 

stages:
  - build
  - type_check
  - test

build-job:
  stage: build
  script:
    - echo "Compiling the code..."
    - echo "Compile complete."

type-check:
  stage: type_check
  script:
    - echo "Running type checking with mypy..."
  #  - pip install mypy  # add this to requirements later
  #  - mypy backend/ --ignore-missing-imports 

test:
  stage: test
  before_script:
    - python -V
    - pip install -r backend/requirements.txt 
    - pip install coverage
  script:
    - echo "Running unit tests... This will take about 60 seconds."
#    - sleep 10
#    - coverage run backend/test_module.py # Running the tests.
#    - coverage report
#  coverage: '/TOTAL.*?(\d+\%)$/'
